### PR TITLE
Create CI / CD actions

### PR DESCRIPTION
**Pull request by BBArikL**
Add CI / CD actions.

### CODE REVIEW

**Comment by BBArikL** [comment]
Needs to merge #4 before confirming this.

**Comment by BBArikL** [comment]
I want at least one review to push to the dev branch. @BiblioLexicus/maintainers

**Comment by xelorax** [comment]
waiting for smth?

**Comment by BBArikL** [comment]
It needs more setup https://banagale.com/running-django-tests-in-github-actions.htm @xelorax

**Comment by BBArikL** [comment]
I need the approval of one person @BiblioLexicus/maintainers 👍 

If you need more things added let me know now

**Pull request merged**
